### ISSUE TITLE
Exception in thread "Skype-Receiver-Thread" java.lang.IllegalArgumentException: Must supply a valid URL

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Delthas/JavaSkype#27] opened 2017-01-11 15:45 UTC
```Exception in thread "Skype-Receiver-Thread" java.lang.IllegalArgumentException: Must supply a valid URL
        at org.jsoup.helper.Validate.notEmpty(Validate.java:102)
        at org.jsoup.helper.HttpConnection.url(HttpConnection.java:72)
        at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:36)
        at org.jsoup.Jsoup.connect(Jsoup.java:73)
        at fr.delthas.skype.WebConnector.sendRequest(WebConnector.java:190)
        at fr.delthas.skype.WebConnector.getAvatar(WebConnector.java:71)
        at fr.delthas.skype.Skype.getAvatar(Skype.java:319)
        at fr.delthas.skype.User.getAvatar(User.java:167)
        at com.mrpowergamerbr.sparklywhistlerbot.SkypeWhistler.lambda$0(SkypeWhistler.java:31)
        at fr.delthas.skype.Skype.groupMessageReceived(Skype.java:434)
        at fr.delthas.skype.NotifConnector.processPacket(NotifConnector.java:241)
        at fr.delthas.skype.NotifConnector.lambda$connect$4(NotifConnector.java:516)
        at java.lang.Thread.run(Thread.java:745)
```

At line 31
```
System.out.println(user.getAvatar());
```

**Comment by Delthas** [comment] 2017-02-07 12:50
Hi! I'm back. I'm trying to fix this but I can't get to reproduce this issue. I never get the exception when printing the avatar of any of my contacts. Does this still happen for you in 1.0.19?

**Comment by MrPowerGamerBR** [comment] 2017-02-07 12:52
@Delthas I didn't test yet because I 100% migrated to Discord after Skype decided to crash for the nth time.

**Comment by Delthas** [comment] 2017-02-07 13:15
@MrPowerGamerBR hahahahaha haha okay

**Comment by Delthas** [comment] 2017-03-23 17:24
Closing the issue since avatar fetching has largely changed since then.

**Closed by Delthas** 2017-03-23 17:24 UTC
